[target.'cfg(all())']
rustflags = [
  "-Dfuture-incompatible",
  "-Dnonstandard-style",
  "-Wunused",
  "-Dmissing_crate_level_docs",
  # "-Dmissing_docs",
  "-Dclippy::all",
  "-Dclippy::pedantic",
  "-Dclippy::nursery",
  "-Dclippy::restriction",
  "-Aclippy::module-name-repetitions",
  "-Aclippy::needless-pass-by-value",
  "-Aclippy::use-self",
  "-Aclippy::implicit-return",
  "-Aclippy::missing_docs_in_private_items",
  "-Aclippy::missing-inline-in-public-items",
  "-Aclippy::shadow_reuse",
  "-Aclippy::shadow_unrelated",
  "-Aclippy::pub-use",
  "-Aclippy::exhaustive_structs",
  "-Aclippy::exhaustive_enums",
  "-Aclippy::unwrap-used",
  "-Aclippy::wildcard-enum-match-arm",
  "-Aclippy::default-trait-access",
  "-Aclippy::arithmetic",
  "-Aclippy::float-arithmetic",
  "-Aclippy::integer-arithmetic",
  "-Aclippy::mod-module-files",
  "-Aclippy::indexing-slicing",
  "-Aclippy::std-instead-of-core",
]
